### ISSUE TITLE
Project root should default to default directory and avoid error

### ISSUE THREAD

**Issue by henrymazza** [ilya-babanov/emacs-bpr#13]
**Use case:** Say you are in *scratch* buffer and try to launch a process with `bpr-use-projectile` enabled. This is gonna fail with “you are not in a project.” 

**What’d be cool:** `bpr-try-get-project-root` should test for `projectile-project-root` being `nil` before failing.

**PS:** I already overrode `bpr-try-get-project-root`. I just want to register the error here. Thanx.

**Comment by iliabv** [comment]
Thanks for the report! Should be fixed now
