### ISSUE TITLE
Completion callbacks

### ISSUE THREAD

**Issue by d12frosted** [ilya-babanov/emacs-bpr#6]
Hey,

Is it possible to assign callbacks to `bpr-spawn`? For example, I want to call (interactively) emacs lisp function `f1` when spawned command completes successfully and `f2` on any error. I looked in documentation and didn't find any information. It might be useful in some automation. 😸 

P. S. Thank you for `bpr` - I use it on daily basis :)

**Comment by iliabv** [comment]
Hello! 

Right now it's impossible to assign callbacks to `bpr-spawn`. 
But I think that it's not hard to implement this feature. I'm going to add two options: `bpr-on-success` and `bpr-on-error`. It would be possible to set them globally or just for specific `bpr-spawn` call. 

I'll update issue when it's ready

**Comment by d12frosted** [comment]
Nice, that would be really nice! Thank you.

~ d12frosted

**Comment by iliabv** [comment]
Hi! Feature has been implemented. 
If it's not exactly what you wanted or if you have some remarks - fell free to tell about it.

**Comment by d12frosted** [comment]
I confirm, this works like a charm. Thank you so much for the update 😸 

P. S. Sorry that it took so long to check this update.
